import type { CollectionConfig } from 'payload'
import { LAB_SELECT_OPTIONS } from '../lib/labs'

const conceptRel = (name: string, label: string, family: string, hasMany = false, required = false) => ({
  name,
  type: 'relationship' as const,
  relationTo: 'concepts' as const,
  hasMany,
  required,
  label,
  filterOptions: { family: { equals: family } },
})

export const Courses: CollectionConfig = {
  slug: 'courses',
  labels: { singular: '课程', plural: '课程' },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'lab', 'gradeMin', 'primaryX', 'primaryY', 'totalHours', 'status'],
    group: '课程',
  },
  access: { read: () => true },
  versions: { drafts: true },
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          label: '基础',
          fields: [
            { name: 'title', type: 'text', required: true, label: '名称' },
            { name: 'subtitle', type: 'text', label: '副标题' },
            { name: 'slug', type: 'text', required: true, unique: true, label: 'URL 标识' },
            { name: 'summary', type: 'textarea', required: true, label: '摘要' },
            { name: 'cover', type: 'upload', relationTo: 'media', label: '封面' },
            { name: 'sampleFlag', type: 'checkbox', label: '示例课程', defaultValue: true },
            {
              type: 'row',
              fields: [
                { name: 'gradeMin', type: 'number', required: true, label: '年级下限', min: 1, max: 12 },
                { name: 'gradeMax', type: 'number', required: true, label: '年级上限', min: 1, max: 12 },
                { name: 'totalHours', type: 'number', required: true, label: '课时' },
              ],
            },
            { name: 'drivingQuestion', type: 'textarea', required: true, label: '驱动性问题' },
            {
              name: 'subjects',
              type: 'select',
              hasMany: true,
              label: '学科',
              options: [
                { label: '语文', value: '语文' },
                { label: '数学', value: '数学' },
                { label: '科学', value: '科学' },
                { label: '科学探究', value: '科学探究' },
                { label: '系统思维', value: '系统思维' },
                { label: '工程设计', value: '工程设计' },
                { label: '智能硬件', value: '智能硬件' },
                { label: 'AI创作', value: 'AI创作' },
                { label: '数字制造', value: '数字制造' },
                { label: '产品思维', value: '产品思维' },
                { label: '三维建模', value: '三维建模' },
                { label: '文化理解', value: '文化理解' },
                { label: '审美表达', value: '审美表达' },
                { label: '规则设计', value: '规则设计' },
                { label: '逻辑推理', value: '逻辑推理' },
                { label: '数据分析', value: '数据分析' },
                { label: '交互设计', value: '交互设计' },
                { label: '叙事表达', value: '叙事表达' },
                { label: '信息技术', value: '信息技术' },
                { label: '人文社科', value: '人文社科' },
                { label: '艺术', value: '艺术' },
                { label: '外语', value: '外语' },
                { label: '劳动/综合实践', value: '综合实践' },
              ],
            },
            {
              name: 'lab',
              type: 'select',
              label: '所属场景',
              options: LAB_SELECT_OPTIONS,
              admin: { description: 'B3.0 九个场景之一。公开浏览脊骨是场景，不是语数英分科。' },
            },
            {
              name: 'labTitle',
              type: 'text',
              label: '研究室',
              admin: { description: '卡片翻转时显示的研究室名称，可与 B3.0 场景名不同。' },
            },
            {
              name: 'research',
              type: 'textarea',
              label: '研究',
              admin: { description: '课程卡片背面的研究说明。' },
            },
            {
              name: 'scene',
              type: 'select',
              label: 'B3.0 场景',
              options: LAB_SELECT_OPTIONS,
            },
            {
              name: 'issue',
              type: 'select',
              label: 'B3.0 议题',
              options: [
                { label: '人与自然', value: 'nature' },
                { label: '人与技术', value: 'tech' },
                { label: '人与人', value: 'people' },
              ],
            },
            {
              name: 'stage',
              type: 'select',
              label: 'B3.0 学段',
              options: [
                { label: 'G1-G3', value: 'g1-3' },
                { label: 'G4-G6', value: 'g4-6' },
                { label: 'G7-G9', value: 'g7-9' },
                { label: 'G10-G12', value: 'g10-12' },
              ],
            },
            {
              name: 'arc',
              type: 'select',
              label: 'B3.0 教学弧',
              options: [
                { label: '探究驱动', value: 'inquiry' },
                { label: '设计思维', value: 'design' },
                { label: '敏捷创造', value: 'agile' },
                { label: '游戏化探险', value: 'game' },
                { label: '社会行动', value: 'action' },
              ],
            },
            {
              name: 'system',
              type: 'select',
              label: '课程体系',
              options: [
                { label: '兴趣体系', value: 'interest' },
                { label: '融合体系', value: 'fusion' },
                { label: '拔创体系', value: 'pioneer' },
              ],
              admin: { description: '课程体系页三个页签。可随时改派。' },
            },
            { name: 'tabOutline', type: 'textarea', label: '理念与纲要补充' },
            { name: 'tabOutcomes', type: 'textarea', label: '课程成果说明' },
          ],
        },
        {
          label: 'B1.0 坐标',
          fields: [
            { name: 'paradigmVersion', type: 'text', defaultValue: 'B3.0', label: '范式版本', required: true },
            conceptRel('primaryX', '主 X 议题', 'X', false, true),
            conceptRel('secondaryX', '辅助 X', 'X', true),
            conceptRel('primaryY', '主 Y 透镜', 'Y', false, true),
            conceptRel('secondaryY', '辅助 Y 透镜', 'Y'),
            conceptRel('targetC', '目标 C', 'C', true, true),
            conceptRel('primaryT', '核心 T 技能构件', 'T', true, true),
            conceptRel('targetL', '目标 L', 'L', false, true),
            conceptRel('teachingArc', '教学弧', 'ARC', false, true),
            conceptRel('domainPathways', '领域路径 A1-A6', 'A', true),
            conceptRel('aiCapabilities', 'AI 能力 A/B/C/D', 'AI', true),
            {
              name: 'trackAffinity',
              type: 'relationship',
              relationTo: 'concepts',
              hasMany: true,
              label: '综合赛道倾向（非认定）',
              filterOptions: { family: { equals: 'TRACK' } },
              admin: { description: '赛道只标注倾向，不做学生结论。' },
            },
          ],
        },
        {
          label: '实施与评价',
          fields: [
            { name: 'modules', type: 'relationship', relationTo: 'course-modules', hasMany: true, label: '模块' },
            { name: 'materials', type: 'textarea', label: '物料' },
            { name: 'hardware', type: 'textarea', label: '硬件' },
            { name: 'software', type: 'textarea', label: '软件' },
            { name: 'safety', type: 'textarea', required: true, label: '安全要求' },
            { name: 'assessments', type: 'textarea', required: true, label: '评价' },
            { name: 'evidence', type: 'textarea', required: true, label: '证据要求' },
            { name: 'gallery', type: 'upload', relationTo: 'media', hasMany: true, label: '过程与成果画廊' },
            {
              type: 'collapsible',
              label: 'C1.3 补充（可选，不得覆盖 B1.0）',
              admin: { initCollapsed: true },
              fields: [
                {
                  name: 'c13_project_maturity',
                  type: 'select',
                  label: 'c13_project_maturity',
                  options: ['P1', 'P2', 'P3', 'P4', 'P5'].map((v) => ({ label: v, value: v })),
                },
                { name: 'c13_ai_breadth', type: 'text', label: 'c13_ai_breadth' },
                {
                  name: 'c13_real_world_intensity',
                  type: 'select',
                  label: 'c13_real_world_intensity（真实世界强度，不是 T 技能）',
                  options: ['T1', 'T2', 'T3', 'T4', 'T5'].map((v) => ({ label: `强度 ${v}`, value: v })),
                  admin: { description: 'C1.3 真实世界强度。禁止称为 T技能。' },
                },
                { name: 'c13_domain_balance', type: 'text', label: 'c13_domain_balance' },
              ],
            },
          ],
        },
        {
          label: '发布',
          fields: [
            {
              name: 'seo',
              type: 'group',
              fields: [
                { name: 'title', type: 'text', label: 'SEO 标题' },
                { name: 'description', type: 'textarea', label: 'SEO 描述' },
              ],
            },
            { name: 'featured', type: 'checkbox', label: '首页精选', defaultValue: false },
            {
              name: 'status',
              type: 'select',
              defaultValue: 'published',
              options: [
                { label: '草稿', value: 'draft' },
                { label: '审核中', value: 'review' },
                { label: '已发布', value: 'published' },
                { label: '已归档', value: 'archived' },
              ],
            },
          ],
        },
      ],
    },
  ],
}
